### ISSUE TITLE
Doesn't build on Raspberry Pi 5 (gcc 12.2.0)

### ISSUE THREAD

**Issue by scruss** [scarybeasts/beebjit#53]
```
./build.sh
In file included from asm/asm_common.c:4:
asm/arm64/asm_common_arm64.c: In function ‘asm_copy’:
asm/arm64/asm_common_arm64.c:12:24: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
   12 |   size_t size = (p_end - p_start);
      |                        ^
At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
In file included from asm/asm_jit.c:4:
asm/arm64/asm_jit_arm64.c: In function ‘asm_jit_start_code_updates’:
asm/arm64/asm_jit_arm64.c:227:20: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
  227 |   p_end = (p_start + length);
      |                    ^
asm/arm64/asm_jit_arm64.c:235:31: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
  235 |   pages_length = (p_pages_end - p_pages_start);
      |                               ^
asm/arm64/asm_jit_arm64.c: In function ‘asm_jit_finish_code_updates’:
asm/arm64/asm_jit_arm64.c:256:59: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
  256 |   __builtin___clear_cache(p_asm->p_start, (p_asm->p_start + p_asm->length));
      |                                                           ^
At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
```

Raspberry Pi 5, 8 GB RAM, running Raspberry Pi OS 64-bit desktop (Debian 12 / aarch64)
gcc (Debian 12.2.0-14) 12.2.0

Curiously, the headless version (`./build_headless_opt.sh`) does compile, but `./beebjit -0 test/perf/clocksp.ssd -fast -headless -terminal` only manages around 1024 MHz. I get a similarly low number on a Mac Mini M2Pro too.

**Comment by scarybeasts** [comment]
Sorry, only just saw this issue!

First things first. The poor performance is because the JIT mode isn't default on ARM64. The ARM64 JIT is now stable, so I made it the default mode. x64 and ARM64 now both default to JIT for consistency. Fixed here: https://github.com/scarybeasts/beebjit/commit/d86d4321b003479c28e5e45dbd62edc44971080a

With that change in place, my M1-based MacBook Air gets 7700MHz on CLOCKSP with -fast.

I'm curious what a Raspberrt Pi 5 can get, i.e. how it compares to the M1.

**Comment by scarybeasts** [comment]
The GCC + ARM build should be fixed here: https://github.com/scarybeasts/beebjit/commit/8f68fd0ee893956ad79cfb7453d0adf35182a05b

I added the same compiler warning flags to the macOS clang build (which I run regularly), so this shouldn't regress in the future. Thanks for the report.
